In [1]:
import pandas as pd

In [3]:
movies = pd.read_csv(filepath_or_buffer='http://bit.ly/imdbratings')

In [4]:
movies.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [10]:
movies_title_genre = pd.read_csv(filepath_or_buffer='http://bit.ly/imdbratings', usecols=['title','genre'])

In [12]:
movies_title_genre.columns = ['t','g']

In [14]:
movies_title_genre.columns

Index(['t', 'g'], dtype='object')

In [16]:
movies.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [25]:
import numpy as np
movies.select_dtypes(np.number)

     star_rating  duration
0            9.3       142
1            9.2       175
2            9.1       200
3            9.0       152
4            8.9       154
5            8.9        96
6            8.9       161
7            8.9       201
8            8.9       195
9            8.9       139
10           8.8       178
11           8.8       148
12           8.8       124
13           8.8       142
14           8.8       179
15           8.7       169
16           8.7       133
17           8.7       207
18           8.7       146
19           8.7       121
20           8.7       136
21           8.7       130
22           8.7       130
23           8.7       106
24           8.7       127
25           8.6       116
26           8.6       175
27           8.6       118
28           8.6       110
29           8.6        87
..           ...       ...
949          7.4       103
950          7.4       108
951          7.4       105
952          7.4       117
953          7.4       102
954          7.4       104
955          7.4       157
956          7.4       104
957          7.4        98
958          7.4       109
959          7.4        96
960          7.4       103
961          7.4       114
962          7.4        99
963          7.4       118
964          7.4       150
965          7.4       105
966          7.4        87
967          7.4       136
968          7.4       162
969          7.4       109
970          7.4       107
971          7.4        90
972          7.4       112
973          7.4       126
974          7.4       116
975          7.4       118
976          7.4       138
977          7.4       114
978          7.4       126

[979 rows x 2 columns]